services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start && npx sequelize-cli init"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE_FILE=/data/db.sqlite